/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JOptionPane;

/**
 *
 * @author adise
 */
public class Mekanik extends javax.swing.JFrame {

    /**
     * Creates new form Mekanik
     */
    public Mekanik() {
        mk = new formDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pilihMekanikLabel = new javax.swing.JLabel();
        noTeleponTextField = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();
        keahlianLabel = new javax.swing.JLabel();
        keahlianTextField = new javax.swing.JTextField();
        lulusanLabel = new javax.swing.JLabel();
        lulusanTextField = new javax.swing.JTextField();
        adiCheckBox = new javax.swing.JCheckBox();
        budiCheckBox = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();
        namaMKTextField = new javax.swing.JTextField();
        namaMekanikLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mekanik");

        jLabel1.setText("No. Telepon");

        pilihMekanikLabel.setText("Pilih Mekanik");

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");

        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        keahlianLabel.setText("Keahlian");

        lulusanLabel.setText("Lulusan");

        adiCheckBox.setText("Adi");
        adiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiCheckBoxActionPerformed(evt);
            }
        });

        budiCheckBox.setText("Budi");
        budiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budiCheckBoxActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        namaMekanikLabel.setText("Nama Mekanik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pilihMekanikLabel)
                                .addComponent(jLabel1)
                                .addComponent(keahlianLabel)
                                .addComponent(lulusanLabel)
                                .addComponent(namaMekanikLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(simpanButton)
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(hapusButton)
                                .addGap(18, 18, 18)
                                .addComponent(kembaliButton)
                                .addGap(18, 18, 18)
                                .addComponent(submitButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(budiCheckBox)
                                        .addComponent(keahlianTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addComponent(lulusanTextField))
                                    .addComponent(adiCheckBox))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaMKTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(noTeleponTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihMekanikLabel)
                    .addComponent(adiCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(budiCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaMKTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaMekanikLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keahlianLabel)
                    .addComponent(keahlianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lulusanLabel)
                    .addComponent(lulusanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanButton)
                    .addComponent(hapusButton)
                    .addComponent(kembaliButton)
                    .addComponent(submitButton))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        MenuUtama MN = new MenuUtama();
        MN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void adiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiCheckBoxActionPerformed
        // TODO add your handling code here:
        if(adiCheckBox.isSelected())
        {
            namaMKTextField.setText("Adi");
            noTeleponTextField.setText("085333000122");
            lulusanTextField.setText("ITB");
            keahlianTextField.setText("Bintang 4");
            adiCheckBox.setSelected(true);
        }else{
            namaMKTextField.setText("");
            noTeleponTextField.setText("");
            lulusanTextField.setText("");
            keahlianTextField.setText("");
            adiCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_adiCheckBoxActionPerformed

    private void budiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budiCheckBoxActionPerformed
        // TODO add your handling code here:
       if(budiCheckBox.isSelected())
        {
            namaMKTextField.setText("Budi");
            noTeleponTextField.setText("087888999000");
            lulusanTextField.setText("IPB");
            keahlianTextField.setText("Bintang 5");
            budiCheckBox.setSelected(true);
        }else{
            namaMKTextField.setText("");
            noTeleponTextField.setText("");
            lulusanTextField.setText("");
            keahlianTextField.setText("");
            budiCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_budiCheckBoxActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        String Id = "";
        String nama_mekanik = namaMKTextField.getText();
        String no_telepon = noTeleponTextField.getText();
        String keahlian = keahlianTextField.getText();
        String lulusan = lulusanTextField.getText();
        
        mk.MekanikDB(Id, nama_mekanik, no_telepon, keahlian, lulusan);
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        //Report rpt = new Report();
        //rpt.setVisible(true);
        //this.dispose();
        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Apakah anda punya keluhan?", "Keluhan", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            Keluhan klhn = new Keluhan();
            klhn.setVisible(true);
            this.dispose();
        }else{
            System.exit(0);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mekanik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mekanik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mekanik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mekanik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mekanik().setVisible(true);
            }
        });
    }
formDB mk;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adiCheckBox;
    private javax.swing.JCheckBox budiCheckBox;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel keahlianLabel;
    private javax.swing.JTextField keahlianTextField;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel lulusanLabel;
    private javax.swing.JTextField lulusanTextField;
    private javax.swing.JTextField namaMKTextField;
    private javax.swing.JLabel namaMekanikLabel;
    private javax.swing.JTextField noTeleponTextField;
    private javax.swing.JLabel pilihMekanikLabel;
    private javax.swing.JButton simpanButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
